### ISSUE TITLE
access_token= Sys.getenv("MAPBOX_ACCESS_TOKEN")??

### ISSUE THREAD

**Issue by yumingzhongsheng** [bhaskarvk/leaflet.mapbox#1]
I am new to interactive maps. I am trying to pass a mapbox tile  into leaflet, but it doesn't seem to work. This is what I have done. 
   library(leaflet.mapbox); packageVersion("leaflet.mapbox")
   leafletMapbox(access_token= Sys.getenv("MAPBOX_ACCESS_TOKEN")) %>%
  addMapboxTileLayer(mapbox.classicStyleIds$satellite)

**Comment by yumingzhongsheng** [comment]
Sorry, I have solved this problem. Like this:
library(leaflet.mapbox); packageVersion("leaflet.mapbox")
leafletMapbox(access_token="pk.eyJ1IjoidGFuZ2thaTY2NiIsImEiOiJjajhsMXZwa3YwanA2MndtenNhc3lma2h5In0.LNxnrcN6Hr-5Zu2FA3VmvA") %>%
  addMapboxTileLayer(mapbox.classicStyleIds$satellite)

**Comment by bhaskarvk** [comment]
You are not supposed to share your key like that. Put something like
`MAPBOX_ACCESS_TOKEN=<your key>` in your $HOME/.Renviron file and then `Sys.getenv('MAPBOX_ACCESS_TOKEN')` will read that from your .Renviron file.
